#!/bin/bash -e
#
# xxxx

GEN_GO_COMMAND="--go_out=. --go_opt=paths=source_relative"
GEN_GRPC_COMMAND="--go-grpc_out=. --go-grpc_opt=require_unimplemented_servers=false,paths=source_relative"
GEN_GATEWAY_COMMAND="--grpc-gateway_out=. --grpc-gateway_opt=paths=source_relative"

#######################################
# Cleanup files from the backup dir
# Globals:
#   BACKUP_DIR
#   ORACLE_SID
# Arguments:
#   None
# Returns:
#   None
#######################################
gen_proto_files() {
  shopt -s globstar
  local proto_files=./**/*.proto
  local proto_folders=()
  for file_name in ${proto_files}; do
    proto_folders+=(${file_name%/*\.proto})
  done

  folders=($(echo "${proto_folders[@]}" | tr ' ' '\n' | sort -u | tr '\n' ' '))
  echo "${folders[@]}"
  shopt -u globstar
}

generate_protobuf_stub() {
  folders=($(gen_proto_files))
  for folder in ${folders[@]}; do
    local gateway_command="${GEN_GATEWAY_COMMAND},grpc_api_configuration=${folder}/service.yaml"
    command_str="protoc ${GEN_GO_COMMAND} ${GEN_GRPC_COMMAND} ${gateway_command} ${folder}/*.proto"
    $command_str
  done
}

generate_protobuf_stub
